# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f50fe969-6d2d-4d67-87b7-749c5e4d7a46";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd:3"
      "noatime"
      "ssd"
      "discard=async"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/f50fe969-6d2d-4d67-87b7-749c5e4d7a46";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd:3"
      "noatime"
      "ssd"
      "discard=async"
      "autodefrag"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/f50fe969-6d2d-4d67-87b7-749c5e4d7a46";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress=zstd:8"
      "noatime"
      "ssd"
      "discard=async"
    ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/f50fe969-6d2d-4d67-87b7-749c5e4d7a46";
    fsType = "btrfs";
    options = [
      "subvol=@var"
      "compress=zstd:3"
      "noatime"
      "ssd"
      "discard=async"
      "autodefrag"
    ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/f50fe969-6d2d-4d67-87b7-749c5e4d7a46";
    fsType = "btrfs";
    options = [
      "subvol=@log"
      "compress=zstd:3"
      "noatime"
      "ssd"
      "discard=async"
      "autodefrag"
    ];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/f50fe969-6d2d-4d67-87b7-749c5e4d7a46";
    fsType = "btrfs";
    options = [
      "subvol=@snapshots"
      "compress=zstd:3"
      "noatime"
      "ssd"
      "discard=async"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BA67-0D3D";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/media/ssd0" = {
    device = "/dev/disk/by-uuid/b3cb05da-a6e5-4c73-9251-0e42daf1285e";
    fsType = "ext4";
    options = [
      "defaults"
      "relatime"
      "discard"
      "nofail"
    ];
  };

  fileSystems."/media/hdd0" = {
    device = "/dev/disk/by-uuid/C69EDCA79EDC90F3";
    fsType = "ntfs";
    options = [
      "noatime"
      "lazytime"
      "prealloc"
      "nofail"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  environment.systemPackages = [
    pkgs.sbctl
    pkgs.e2fsprogs
  ];

  boot = {
    loader.systemd-boot.enable = lib.mkForce false;
    loader.efi.canTouchEfiVariables = true;
    lanzaboote = {
      enable = true;
      pkiBundle = "/var/lib/sbctl";
    };
  };

  boot.kernelPackages = pkgs.linuxPackages_latest;
}
