# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f50fe969-6d2d-4d67-87b7-749c5e4d7a46";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/f50fe969-6d2d-4d67-87b7-749c5e4d7a46";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/f50fe969-6d2d-4d67-87b7-749c5e4d7a46";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/f50fe969-6d2d-4d67-87b7-749c5e4d7a46";
    fsType = "btrfs";
    options = [ "subvol=@var" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/f50fe969-6d2d-4d67-87b7-749c5e4d7a46";
    fsType = "btrfs";
    options = [ "subvol=@log" ];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/f50fe969-6d2d-4d67-87b7-749c5e4d7a46";
    fsType = "btrfs";
    options = [ "subvol=@snapshots" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BA67-0D3D";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  environment.systemPackages = [ pkgs.sbctl ];

  boot = {
    loader.systemd-boot.enable = lib.mkForce false;
    loader.efi.canTouchEfiVariables = true;
    lanzaboote = {
      enable = true;
      pkiBundle = "/var/lib/sbctl";
    };
  };

  boot.kernelPackages = pkgs.linuxPackages_latest;
}
